NAME = Replace

FLAGS = -Wall -Werror -Wextra

all:
	@clear
	@c++ main.cpp $(FLAGS) -o $(NAME)
	@echo Good to go
	

clean:
	@clear
	@rm -f $(NAME)
	@echo output files removed

fclean: clean

re: clean all