NAME = megaphone

FLAGS = -Wall -Werror -Wextra -std=c++98

all:
	@clear
	@c++ megaphone.cpp $(FLAGS) -o $(NAME)
	@echo Good to go
	

clean:
	@clear
	@rm -f $(NAME)
	@echo output files removed

fclean: clean

re: clean all